### PR TITLE
move codenvy-release profile to root so can...

### PR DESCRIPTION
**Pull request by nickboldt**
move codenvy-release profile to root so can be used for all downstream
poms/jars

Change-Id: I2af7b59435991120cdd965bd5cd7ee777fd705b6
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
In an attempt to add the codenvy-release profile to the root so it applies to all the child modules, I've created this PR with an extra commit vs. #60.

It worked locally when I commented out the gpg signing thing, since I don't have your keys.

With it enabled, I get:

```
[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ maven-parent-pom-root ---
gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available
```

**Comment by skabashnyuk** [comment]
@nickboldt could you remind me: what issue you are trying to solve with 3d opened PR in this repo?  I'm a bit lost.

**Comment by skabashnyuk** [comment]
@nickboldt could you remind me: what issue you are trying to solve with 3d opened PR in this repo?  I'm a bit lost.

**Comment by nickboldt** [comment]
This is an attempt to ensure publishing/release/deployment works, per your comment here:

>  I guess we need Roman to prove or decline my release assumption. I think eclipse-license-resource-bundle/pom.xml artifact would not be released because it has no parent link.

 -- https://github.com/eclipse/che-parent/pull/60#issuecomment-401106257

**Comment by skabashnyuk** [comment]
No no. That is the issue from your previous pr. I'm interested in an original problem that you are trying to solve. Actually making each time new PR didn't help in this process.

**Comment by nickboldt** [comment]
This PR is the same as #60, but with **one extra commit to fix the thing you suggested I verify works** in #60. I tried to push another commit to #60 but git refused, so I created a new one. This also means you can check out both and diff them if you'd like. 

Please have a look at the commit messages, they explain the series of commits and what's being fixed. 

If you like all this you can of course squash them down to something simpler. 

Since I can only test this to the point where pgp signing fails, and I can't actually publish to nexus, I don't know for sure if this proposed merge works. Need you and @riuvshin to review / test it with your signing key and nexus access.

**Comment by nickboldt** [comment]
> Create an issue where you can describe you thecnical problem or feature request.

I thought we did this in https://github.com/eclipse/che/issues/10216 ?

> If there is only one issue than I hope to see only one PR.

Agreed, that's generally how I work too.

> Keep pushing you changes (whout force ) in same branch of same PR.

That was what I intended with #60, but git glitched on me and refused to let me push to the topic branch. I'm not sure why. But the workaround was to create a new, uncorrupted topic branch. Sorry for the confusion.

**Comment by nickboldt** [comment]
If the above is insufficient, I'll open a new issue on Monday to better explain why merging the repos is a good idea. :) Have a good weekend! 

(Honestly, I'm not trying to be difficult or make your life harder!)

**Comment by skabashnyuk** [comment]
@nickboldt I've talked with @riuvshin and we are not very happy from moving release profile back and forth. I'm going to create separate pr specifically for https://github.com/eclipse/che/issues/10216

**Comment by riuvshin** [comment]
should we close this PR?

**Comment by nickboldt** [comment]
With #62 merged, this is out of date.

**Pull request closed without merging**
