### PR TITLE
WIP DO NOT MERGE 16732 - all-in-one build profile for parent, docs, dashbord, workspace loader and che server

### PR DESCRIPTION
**Pull request by nickboldt**
https://github.com/eclipse/che/issues/16732 - provide a profile that can build all 5 che projects in a single reactor

Change-Id: I114ee8411b5ddc284c19cc964fdc6837907c3575
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
when all projects are already checked out, this change should allow us to build Che from the parent pom like this:

```
mvn clean install -Pserver
```

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Che parent POM                                                     [pom]
[INFO] Che Dependency Management POM                                      [pom]
[INFO] Che :: Docs War                                                    [war]
[INFO] Che Dashboard :: Web App                                           [war]
[INFO] Che Workspace Loader :: Web App                                    [pom]
[INFO] Che Parent                                                         [pom]
[INFO] Che Core Parent                                                    [pom]
[INFO] Che Core :: Commons :: Parent                                      [pom]
[INFO] Che Core :: Commons :: Annotations                                 [jar]
[INFO] Che Core :: Commons :: Java API extension classes                  [jar]
[INFO] Che Core :: API :: DTO                                             [jar]
[INFO] Che Core :: Commons :: Json helpers                                [jar]
[INFO] Che Core :: Commons :: Utilities for tests                         [jar]
[INFO] Che Core :: Commons :: Dependency Injecting                        [jar]
[INFO] Che Core :: Commons :: Scheduler service                           [jar]
[INFO] Che Core :: API :: DTO Maven Plugin                       [maven-plugin]
[INFO] Che Core :: API :: Core                                            [jar]
[INFO] Che Core :: Commons :: Commons Logback                             [jar]
[INFO] Che Core :: Commons :: XML                                         [jar]
[INFO] Che Core :: Commons :: Commons J2ee                                [jar]
[INFO] Che Core :: Commons :: Tracing and Monitoring wrapper              [jar]
[INFO] Che Core :: Commons :: Mail sender                                 [jar]
[INFO] Che Core :: Commons :: Tracing                                     [jar]
[INFO] Che Core :: API :: TypeScript DTO maven plugin            [maven-plugin]
[INFO] Che Core :: API :: Model                                           [jar]
[INFO] Che Core :: DB                                                     [jar]
[INFO] Che Core :: DB :: Vendor H2                                        [jar]
[INFO] Che Core :: DB :: Vendor MySQL                                     [jar]
[INFO] Che Core :: DB :: Vendor PostgreSQL                                [jar]
[INFO] Che Core :: Tracing :: Core                                        [jar]
[INFO] Che Core :: Tracing :: Web                                         [jar]
[INFO] Che Core :: Metrics :: Core                                        [jar]
[INFO] Che Core :: Tracing :: Metrics                                     [jar]
[INFO] Che Master Parent                                                  [pom]
[INFO] Che Core :: API :: Workspace :: Shared                             [jar]
[INFO] Che Core :: API :: Installer :: Shared                             [jar]
[INFO] Che Core :: API :: Authentication :: Shared                        [jar]
[INFO] Che Core :: API :: Authentication                                  [jar]
[INFO] Che Core :: API :: Authentication Github                           [jar]
[INFO] Che Core :: API :: Authentication OpenShift                        [jar]
[INFO] Che Core :: SQL :: Schema                                          [jar]
[INFO] Che Core :: API :: Account                                         [jar]
[INFO] Che Core :: API :: System Shared                                   [jar]
[INFO] Che Core :: API :: System                                          [jar]
[INFO] Che Core :: API :: SSH :: Shared                                   [jar]
[INFO] Che Core :: API :: User :: Shared                                  [jar]
[INFO] Che Core :: API :: User                                            [jar]
[INFO] Che Core :: API :: SSH                                             [jar]
[INFO] Che Core :: API :: Workspace                                       [jar]
[INFO] Che Multiuser :: Parent                                            [pom]
[INFO] Che Multiuser :: API Parent                                        [pom]
[INFO] Che Multiuser :: Permissions :: Shared                             [jar]
[INFO] Che Multiuser :: Sql Schema                                        [jar]
[INFO] Che Multiuser :: Permissions API                                   [jar]
[INFO] Che Multiuser :: Permissions Parent                                [pom]
[INFO] Che Multiuser :: Workspace Permissions                             [jar]
[INFO] Che Core :: Workspace Activity                                     [jar]
[INFO] Che Core :: API :: Factory :: Shared                               [jar]
[INFO] Che Multiuser :: API :: Authentication Commons                     [jar]
[INFO] Che Multiuser :: API :: Authorization                              [jar]
[INFO] Che Multiuser :: Machine Auth Parent                               [pom]
[INFO] Che Multiuser :: Machine Authentication Shared                     [jar]
[INFO] Che Multiuser :: Machine Authentication                            [jar]
[INFO] Che Infrastructures Parent                                         [pom]
[INFO] Infrastructure :: Kubernetes                                       [jar]
[INFO] Che Core :: API :: Factory                                         [jar]
[INFO] Che Core :: API :: Factory Resolver Github                         [jar]
[INFO] Che Core :: API :: Impl Local                                      [jar]
[INFO] Integration Tests :: Parent                                        [pom]
[INFO] Integration Tests :: Cascade Removal                               [jar]
[INFO] Che Core :: API :: Logger :: Shared                                [jar]
[INFO] Che Core :: API :: Logger                                          [jar]
[INFO] Che Core :: API :: Metrics                                         [jar]
[INFO] Che Multiuser :: API :: Authorization Impl                         [jar]
[INFO] Che Multiuser :: Resource :: Shared                                [jar]
[INFO] Che Multiuser :: Resource                                          [jar]
[INFO] Che Multiuser :: Organization :: Shared                            [jar]
[INFO] Che Multiuser :: Organization                                      [jar]
[INFO] Che Multiuser :: JGroups API Implementation                        [jar]
[INFO] Che Multiuser :: Workspace Activity                                [jar]
[INFO] Che Multiuser :: User Permissions                                  [jar]
[INFO] Che Multiuser :: Devfile Permissions                               [jar]
[INFO] Che Multiuser :: Workspace Activity Permissions                    [jar]
[INFO] Che Multiuser :: Factory Permissions                               [jar]
[INFO] Che Multiuser :: System Permissions                                [jar]
[INFO] Che Multiuser :: Resource :: Permissions                           [jar]
[INFO] Che Multiuser :: Logger Permissions                                [jar]
[INFO] Che Multiuser :: Kubernetes Infrastructure Permissions             [jar]
[INFO] Che Multiuser :: Keycloak Integration Parent                       [pom]
[INFO] Che Multiuser :: Keycloak Shared module                            [jar]
[INFO] Che Multiuser :: Personal account                                  [jar]
[INFO] Che Multiuser :: Keycloak Server                                   [jar]
[INFO] Che Multiuser :: Keycloak Token Provider                           [jar]
[INFO] Che Multiuser :: Integration Tests                                 [pom]
[INFO] Che Multiuser :: Integration Cascade                               [jar]
[INFO] Che Multiuser :: PostgreSQL Tck                                    [jar]
[INFO] Che Multiuser :: MYSQL Tck Tests                                   [jar]
[INFO] Infrastructure :: OpenShift                                        [jar]
[INFO] Infrastructure :: Metrics                                          [jar]
[INFO] Che Assembly :: Parent                                             [pom]
[INFO] Che IDE :: Assemblies Swagger WAR                                  [war]
[INFO] Che IDE :: Compiling WS Master WAR                                 [war]
[INFO] Che IDE :: War Packaging                                           [war]
[INFO] Che Workspace Loader :: War Packaging                              [war]
[INFO] Che IDE :: Dashboard Packaging                                     [war]
[INFO] Che IDE :: Assemblies Che Tomcat8                                  [jar]
[INFO] Che IDE :: Assemblies Tomcat                                       [pom]
[INFO] Che Legacy E2E :: Parent                                           [pom]
[INFO] Che Legacy E2E :: Core                                             [jar]
[INFO] Che Legacy E2E :: Test                                             [jar]
[INFO] 
[INFO] --------------< org.eclipse.che.parent:maven-parent-pom >---------------
[INFO] Building Che parent POM 7.12.0-SNAPSHOT                          [1/110]
[INFO] --------------------------------[ pom ]---------------------------------
```

**Comment by nickboldt** [comment]
Good point, git (sub)modules would achieve the same thing AND remove the need for <relativePath> descriptors for parent poms.

**Comment by nickboldt** [comment]
> Lets discuss this approach on next Community call

Added to agenda: 

https://docs.google.com/document/d/1duuavOXVAJNbzU8nIltraDKx5YH2Z34Qwx7AeLnhhzU/edit#

**Comment by skabashnyuk** [comment]
@nickboldt  @benoitf  please review alternatives https://www.eclipse.org/lists/che-dev/msg03720.html

**Pull request closed without merging**
